# __2.0 Data Preparation__

## __2.1 Import Libraries__

In [1]:
# Import the necessary libraries

import pandas as pd

## __2.2 Data Extraction__

The `DataExtractor` class manages data loading and preprocessing for the Tanzanian Water Wells project. It loads training and test data, merges them, and renames the test data, returning the resulting datasets as a tuple.

In [2]:
class DataExtractor:
    """
    This class handles data importation and preprocessing for the Tanzanian Water Wells project.
    """

    def load_data(self):
        """
        Loads and combines training data, and renames test data.

        Returns:
            tuple: A tuple containing the training set (DataFrame) and test set (DataFrame).
        """

        # Load data from CSVs
        df_labels = pd.read_csv("data/training-set-labels.csv")
        df_values = pd.read_csv("data/training-set-values.csv")

        # Combine training set values and labels using a left join
        df_train = df_values.merge(df_labels, on="id", how="left")
        df_train.to_csv("data/train_set.csv", index=False) 

        # Rename test data
        df_test = pd.read_csv("data/test-set-values.csv")
        df_test.to_csv("data/test_set.csv", index=False)

        return df_train, df_test



extractor = DataExtractor()

train_data, test_data = extractor.load_data()

In [3]:
print("Training data shape:", train_data.shape)


print(train_data.head().to_markdown(index=False, numalign='left', stralign='left'))

Training data shape: (59400, 41)
| id    | amount_tsh   | date_recorded   | funder       | gps_height   | installer    | longitude   | latitude   | wpt_name             | num_private   | basin                   | subvillage   | region   | region_code   | district_code   | lga       | ward       | population   | public_meeting   | recorded_by             | scheme_management   | scheme_name                 | permit   | construction_year   | extraction_type   | extraction_type_group   | extraction_type_class   | management   | management_group   | payment        | payment_type   | water_quality   | quality_group   | quantity     | quantity_group   | source               | source_type          | source_class   | waterpoint_type             | waterpoint_type_group   | status_group   |
|:------|:-------------|:----------------|:-------------|:-------------|:-------------|:------------|:-----------|:---------------------|:--------------|:------------------------|:-------------|:---------|:--------------|:----------------|:----------|:-----------|:-------------|:-----------------|:------------------------|:--------------------|:----------------------------|:---------|:--------------------|:------------------|:------------------------|:------------------------|:-------------|:-------------------|:---------------|:---------------|:----------------|:----------------|:-------------|:-----------------|:---------------------|:---------------------|:---------------|:----------------------------|:------------------------|:---------------|
| 69572 | 6000         | 2011-03-14      | Roman        | 1390         | Roman        | 34.9381     | -9.85632   | none                 | 0             | Lake Nyasa              | Mnyusi B     | Iringa   | 11            | 5               | Ludewa    | Mundindi   | 109          | 1                | GeoData Consultants Ltd | VWC                 | Roman                       | False    | 1999                | gravity           | gravity                 | gravity                 | vwc          | user-group         | pay annually   | annually       | soft            | good            | enough       | enough           | spring               | spring               | groundwater    | communal standpipe          | communal standpipe      | functional     |
| 8776  | 0            | 2013-03-06      | Grumeti      | 1399         | GRUMETI      | 34.6988     | -2.14747   | Zahanati             | 0             | Lake Victoria           | Nyamara      | Mara     | 20            | 2               | Serengeti | Natta      | 280          | nan              | GeoData Consultants Ltd | Other               | nan                         | True     | 2010                | gravity           | gravity                 | gravity                 | wug          | user-group         | never pay      | never pay      | soft            | good            | insufficient | insufficient     | rainwater harvesting | rainwater harvesting | surface        | communal standpipe          | communal standpipe      | functional     |
| 34310 | 25           | 2013-02-25      | Lottery Club | 686          | World vision | 37.4607     | -3.82133   | Kwa Mahundi          | 0             | Pangani                 | Majengo      | Manyara  | 21            | 4               | Simanjiro | Ngorika    | 250          | 1                | GeoData Consultants Ltd | VWC                 | Nyumba ya mungu pipe scheme | True     | 2009                | gravity           | gravity                 | gravity                 | vwc          | user-group         | pay per bucket | per bucket     | soft            | good            | enough       | enough           | dam                  | dam                  | surface        | communal standpipe multiple | communal standpipe      | functional     |
| 67743 | 0            | 2013-01-28      | Unicef       | 263          | UNICEF       | 38.4862     | -11.1553   | Zahanati Ya Nanyumbu | 0             | Ruvuma / Southern Coast | Mahakamani   | Mtwara   | 90            | 63              | Nanyumbu  | Nanyumbu   | 58           | 1                | GeoData Consultants Ltd | VWC                 | nan                         | True     | 1986                | submersible       | submersible             | submersible             | vwc          | user-group         | never pay      | never pay      | soft            | good            | dry          | dry              | machine dbh          | borehole             | groundwater    | communal standpipe multiple | communal standpipe      | non functional |
| 19728 | 0            | 2011-07-13      | Action In A  | 0            | Artisan      | 31.1308     | -1.82536   | Shuleni              | 0             | Lake Victoria           | Kyanyamisa   | Kagera   | 18            | 1               | Karagwe   | Nyakasimbi | 0            | 1                | GeoData Consultants Ltd | nan                 | nan                         | True     | 0                   | gravity           | gravity                 | gravity                 | other        | other              | never pay      | never pay      | soft            | good            | seasonal     | seasonal         | rainwater harvesting | rainwater harvesting | surface        | communal standpipe          | communal standpipe      | functional     |

In [4]:

print("Test data shape:", test_data.shape)


print(test_data.head().to_markdown(index=False, numalign='left', stralign='left'))

Test data shape: (14850, 40)
| id    | amount_tsh   | date_recorded   | funder                 | gps_height   | installer   | longitude   | latitude   | wpt_name                | num_private   | basin                   | subvillage   | region   | region_code   | district_code   | lga           | ward         | population   | public_meeting   | recorded_by             | scheme_management   | scheme_name    | permit   | construction_year   | extraction_type   | extraction_type_group   | extraction_type_class   | management   | management_group   | payment     | payment_type   | water_quality   | quality_group   | quantity     | quantity_group   | source               | source_type          | source_class   | waterpoint_type    | waterpoint_type_group   |
|:------|:-------------|:----------------|:-----------------------|:-------------|:------------|:------------|:-----------|:------------------------|:--------------|:------------------------|:-------------|:---------|:--------------|:----------------|:--------------|:-------------|:-------------|:-----------------|:------------------------|:--------------------|:---------------|:---------|:--------------------|:------------------|:------------------------|:------------------------|:-------------|:-------------------|:------------|:---------------|:----------------|:----------------|:-------------|:-----------------|:---------------------|:---------------------|:---------------|:-------------------|:------------------------|
| 50785 | 0            | 2013-02-04      | Dmdd                   | 1996         | DMDD        | 35.2908     | -4.0597    | Dinamu Secondary School | 0             | Internal                | Magoma       | Manyara  | 21            | 3               | Mbulu         | Bashay       | 321          | 1                | GeoData Consultants Ltd | Parastatal          | nan            | 1        | 2012                | other             | other                   | other                   | parastatal   | parastatal         | never pay   | never pay      | soft            | good            | seasonal     | seasonal         | rainwater harvesting | rainwater harvesting | surface        | other              | other                   |
| 51630 | 0            | 2013-02-04      | Government Of Tanzania | 1569         | DWE         | 36.6567     | -3.30921   | Kimnyak                 | 0             | Pangani                 | Kimnyak      | Arusha   | 2             | 2               | Arusha Rural  | Kimnyaki     | 300          | 1                | GeoData Consultants Ltd | VWC                 | TPRI pipe line | 1        | 2000                | gravity           | gravity                 | gravity                 | vwc          | user-group         | never pay   | never pay      | soft            | good            | insufficient | insufficient     | spring               | spring               | groundwater    | communal standpipe | communal standpipe      |
| 17168 | 0            | 2013-02-01      | nan                    | 1567         | nan         | 34.7679     | -5.00434   | Puma Secondary          | 0             | Internal                | Msatu        | Singida  | 13            | 2               | Singida Rural | Puma         | 500          | 1                | GeoData Consultants Ltd | VWC                 | P              | nan      | 2010                | other             | other                   | other                   | vwc          | user-group         | never pay   | never pay      | soft            | good            | insufficient | insufficient     | rainwater harvesting | rainwater harvesting | surface        | other              | other                   |
| 45559 | 0            | 2013-01-22      | Finn Water             | 267          | FINN WATER  | 38.058      | -9.41867   | Kwa Mzee Pange          | 0             | Ruvuma / Southern Coast | Kipindimbi   | Lindi    | 80            | 43              | Liwale        | Mkutano      | 250          | nan              | GeoData Consultants Ltd | VWC                 | nan            | 1        | 1987                | other             | other                   | other                   | vwc          | user-group         | unknown     | unknown        | soft            | good            | dry          | dry              | shallow well         | shallow well         | groundwater    | other              | other                   |
| 49871 | 500          | 2013-03-27      | Bruder                 | 1260         | BRUDER      | 35.0061     | -10.9504   | Kwa Mzee Turuka         | 0             | Ruvuma / Southern Coast | Losonga      | Ruvuma   | 10            | 3               | Mbinga        | Mbinga Urban | 60           | nan              | GeoData Consultants Ltd | Water Board         | BRUDER         | 1        | 2000                | gravity           | gravity                 | gravity                 | water board  | user-group         | pay monthly | monthly        | soft            | good            | enough       | enough           | spring               | spring               | groundwater    | communal standpipe | communal standpipe      |

## __2.3 Data Overview__

The `DataOverview` class, inheriting from `DataExtractor`, furnishes methods to comprehensively examine both the training and test datasets. It presents various insights including basic information, the first and last rows, descriptive statistics, duplicate rows count, unique values per column, and the percentage of missing/null values per column.

In [5]:
class DataOverview(DataExtractor):
    """
    This class inherits from DataExtractor and provides methods for overviewing the 
    training and test datasets.
    """

    def show_overview(self, df, dataset_name="Dataset"):
        """
        Displays a comprehensive overview of a given dataset.

        Args:
            df (DataFrame): The DataFrame containing the data.
            dataset_name (str): A name to identify the dataset in the output. Defaults to "Dataset".
        """
        print(f"\n--- Overview of {dataset_name} ---\n")

        # Basic Info
        print("Info:")
        print(df.info())

        # First 5 and Last 5 Rows
        print("\nFirst 5 Rows:")
        print(df.head().to_markdown(index=False, numalign='left', stralign='left'))
        print("\nLast 5 Rows:")
        print(df.tail().to_markdown(index=False, numalign='left', stralign='left'))

        # Descriptive Statistics
        print("\nDescriptive Statistics:")
        print(df.describe().to_markdown(numalign='left', stralign='left'))

        # Duplicate Rows
        num_duplicates = df.duplicated().sum()
        print(f"\nNumber of Duplicate Rows: {num_duplicates}")

        # Unique Values Percentage
        unique_counts = df.nunique()
        print("\nNumber of Unique Values per Column:")
        print(unique_counts.to_markdown(numalign='left', stralign='left'))

        # Missing and Null Values Percentage
        missing_pct = (df.isnull().sum() / df.shape[0] * 100).round(2)
        print("\nPercentage of Missing/Null Values per Column:")
        print(missing_pct.to_markdown(numalign='left', stralign='left'))



# Create the DataOverview instance
overview = DataOverview()

# Load the training and test data
train_data, test_data = overview.load_data()

In [6]:
# Show overviews
overview.show_overview(train_data, "Training Set")

--- Overview of Training Set ---

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 41 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   amount_tsh             59400 non-null  float64
 2   date_recorded          59400 non-null  object
 3   funder                 55763 non-null  object
 4   gps_height             59400 non-null  int64
 5   installer              55745 non-null  object
 6   longitude              59400 non-null  float64
 7   latitude               59400 non-null  float64
 8   wpt_name               59398 non-null  object
 9   num_private            59400 non-null  int64
 10  basin                  59400 non-null  object
 11  subvillage             59029 non-null  object
 12  region                 59400 non-null  object
 13  region_code            59400 non-null  int64
 14  district_code          59400 non-null  int64
 15  lga                    59400 non-null  object
 16  ward                   59400 non-null  object
 17  population             59400 non-null  int64
 18  public_meeting         56066 non-null  object
 19  recorded_by            59400 non-null  object
 20  scheme_management      55522 non-null  object
 21  scheme_name            30590 non-null  object
 22  permit                 56344 non-null  object
 23  construction_year      59400 non-null  int64
 24  extraction_type        59400 non-null  object
 25  extraction_type_group  59400 non-null  object
 26  extraction_type_class  59400 non-null  object
 27  management             59400 non-null  object
 28  management_group       59400 non-null  object
 29  payment                59400 non-null  object
 30  payment_type           59400 non-null  object
 31  water_quality          59400 non-null  object
 32  quality_group          59400 non-null  object
 33  quantity               59400 non-null  object
 34  quantity_group         59400 non-null  object
 35  source                 59400 non-null  object
 36  source_type            59400 non-null  object
 37  source_class           59400 non-null  object
 38  waterpoint_type        59400 non-null  object
 39  waterpoint_type_group  59400 non-null  object
 40  status_group           59400 non-null  object
dtypes: float64(3), int64(7), object(31)
memory usage: 18.6+ MB
None

First 5 Rows:
| id    | amount_tsh   | date_recorded   | funder       | gps_height   | installer    | longitude   | latitude   | wpt_name             | num_private   | basin                   | subvillage   | region   | region_code   | district_code   | lga       | ward       | population   | public_meeting   | recorded_by             | scheme_management   | scheme_name                 | permit   | construction_year   | extraction_type   | extraction_type_group   | extraction_type_class   | management   | management_group   | payment        | payment_type   | water_quality   | quality_group   | quantity     | quantity_group   | source               | source_type          | source_class   | waterpoint_type             | waterpoint_type_group   | status_group   |
|:------|:-------------|:----------------|:-------------|:-------------|:-------------|:------------|:-----------|:---------------------|:--------------|:------------------------|:-------------|:---------|:--------------|:----------------|:----------|:-----------|:-------------|:-----------------|:------------------------|:--------------------|:----------------------------|:---------|:--------------------|:------------------|:------------------------|:------------------------|:-------------|:-------------------|:---------------|:---------------|:----------------|:----------------|:-------------|:-----------------|:---------------------|:---------------------|:---------------|:----------------------------|:------------------------|:---------------|
| 69572 | 6000         | 2011-03-14      | Roman        | 1390         | Roman        | 34.9381     | -9.85632   | none                 | 0             | Lake Nyasa              | Mnyusi B     | Iringa   | 11            | 5               | Ludewa    | Mundindi   | 109          | 1                | GeoData Consultants Ltd | VWC                 | Roman                       | False    | 1999                | gravity           | gravity                 | gravity                 | vwc          | user-group         | pay annually   | annually       | soft            | good            | enough       | enough           | spring               | spring               | groundwater    | communal standpipe          | communal standpipe      | functional     |
| 8776  | 0            | 2013-03-06      | Grumeti      | 1399         | GRUMETI      | 34.6988     | -2.14747   | Zahanati             | 0             | Lake Victoria           | Nyamara      | Mara     | 20            | 2               | Serengeti | Natta      | 280          | nan              | GeoData Consultants Ltd | Other               | nan                         | True     | 2010                | gravity           | gravity                 | gravity                 | wug          | user-group         | never pay      | never pay      | soft            | good            | insufficient | insufficient     | rainwater harvesting | rainwater harvesting | surface        | communal standpipe          | communal standpipe      | functional     |
| 34310 | 25           | 2013-02-25      | Lottery Club | 686          | World vision | 37.4607     | -3.82133   | Kwa Mahundi          | 0             | Pangani                 | Majengo      | Manyara  | 21            | 4               | Simanjiro | Ngorika    | 250          | 1                | GeoData Consultants Ltd | VWC                 | Nyumba ya mungu pipe scheme | True     | 2009                | gravity           | gravity                 | gravity                 | vwc          | user-group         | pay per bucket | per bucket     | soft            | good            | enough       | enough           | dam                  | dam                  | surface        | communal standpipe multiple | communal standpipe      | functional     |
| 67743 | 0            | 2013-01-28      | Unicef       | 263          | UNICEF       | 38.4862     | -11.1553   | Zahanati Ya Nanyumbu | 0             | Ruvuma / Southern Coast | Mahakamani   | Mtwara   | 90            | 63              | Nanyumbu  | Nanyumbu   | 58           | 1                | GeoData Consultants Ltd | VWC                 | nan                         | True     | 1986                | submersible       | submersible             | submersible             | vwc          | user-group         | never pay      | never pay      | soft            | good            | dry          | dry              | machine dbh          | borehole             | groundwater    | communal standpipe multiple | communal standpipe      | non functional |
| 19728 | 0            | 2011-07-13      | Action In A  | 0            | Artisan      | 31.1308     | -1.82536   | Shuleni              | 0             | Lake Victoria           | Kyanyamisa   | Kagera   | 18            | 1               | Karagwe   | Nyakasimbi | 0            | 1                | GeoData Consultants Ltd | nan                 | nan                         | True     | 0                   | gravity           | gravity                 | gravity                 | other        | other              | never pay      | never pay      | soft            | good            | seasonal     | seasonal         | rainwater harvesting | rainwater harvesting | surface        | communal standpipe          | communal standpipe      | functional     |

Last 5 Rows:
| id    | amount_tsh   | date_recorded   | funder          | gps_height   | installer   | longitude   | latitude   | wpt_name            | num_private   | basin       | subvillage   | region      | region_code   | district_code   | lga            | ward             | population   | public_meeting   | recorded_by             | scheme_management   | scheme_name                 | permit   | construction_year   | extraction_type   | extraction_type_group   | extraction_type_class   | management   | management_group   | payment               | payment_type   | water_quality   | quality_group   | quantity     | quantity_group   | source       | source_type   | source_class   | waterpoint_type    | waterpoint_type_group   | status_group   |
|:------|:-------------|:----------------|:----------------|:-------------|:------------|:------------|:-----------|:--------------------|:--------------|:------------|:-------------|:------------|:--------------|:----------------|:---------------|:-----------------|:-------------|:-----------------|:------------------------|:--------------------|:----------------------------|:---------|:--------------------|:------------------|:------------------------|:------------------------|:-------------|:-------------------|:----------------------|:---------------|:----------------|:----------------|:-------------|:-----------------|:-------------|:--------------|:---------------|:-------------------|:------------------------|:---------------|
| 60739 | 10           | 2013-05-03      | Germany Republi | 1210         | CES         | 37.1698     | -3.25385   | Area Three Namba 27 | 0             | Pangani     | Kiduruni     | Kilimanjaro | 3             | 5               | Hai            | Masama Magharibi | 125          | True             | GeoData Consultants Ltd | Water Board         | Losaa Kia water supply      | True     | 1999                | gravity           | gravity                 | gravity                 | water board  | user-group         | pay per bucket        | per bucket     | soft            | good            | enough       | enough           | spring       | spring        | groundwater    | communal standpipe | communal standpipe      | functional     |
| 27263 | 4700         | 2011-05-07      | Cefa-njombe     | 1212         | Cefa        | 35.25       | -9.07063   | Kwa Yahona Kuvala   | 0             | Rufiji      | Igumbilo     | Iringa      | 11            | 4               | Njombe         | Ikondo           | 56           | True             | GeoData Consultants Ltd | VWC                 | Ikondo electrical water sch | True     | 1996                | gravity           | gravity                 | gravity                 | vwc          | user-group         | pay annually          | annually       | soft            | good            | enough       | enough           | river        | river/lake    | surface        | communal standpipe | communal standpipe      | functional     |
| 37057 | 0            | 2011-04-11      | nan             | 0            | nan         | 34.0171     | -8.75043   | Mashine             | 0             | Rufiji      | Madungulu    | Mbeya       | 12            | 7               | Mbarali        | Chimala          | 0            | True             | GeoData Consultants Ltd | VWC                 | nan                         | False    | 0                   | swn 80            | swn 80                  | handpump                | vwc          | user-group         | pay monthly           | monthly        | fluoride        | fluoride        | enough       | enough           | machine dbh  | borehole      | groundwater    | hand pump          | hand pump               | functional     |
| 31282 | 0            | 2011-03-08      | Malec           | 0            | Musa        | 35.8613     | -6.37857   | Mshoro              | 0             | Rufiji      | Mwinyi       | Dodoma      | 1             | 4               | Chamwino       | Mvumi Makulu     | 0            | True             | GeoData Consultants Ltd | VWC                 | nan                         | True     | 0                   | nira/tanira       | nira/tanira             | handpump                | vwc          | user-group         | never pay             | never pay      | soft            | good            | insufficient | insufficient     | shallow well | shallow well  | groundwater    | hand pump          | hand pump               | functional     |
| 26348 | 0            | 2011-03-23      | World Bank      | 191          | World       | 38.104      | -6.74746   | Kwa Mzee Lugawa     | 0             | Wami / Ruvu | Kikatanyemba | Morogoro    | 5             | 2               | Morogoro Rural | Ngerengere       | 150          | True             | GeoData Consultants Ltd | VWC                 | nan                         | True     | 2002                | nira/tanira       | nira/tanira             | handpump                | vwc          | user-group         | pay when scheme fails | on failure     | salty           | salty           | enough       | enough           | shallow well | shallow well  | groundwater    | hand pump          | hand pump               | functional     |

Descriptive Statistics:
|       | id      | amount_tsh   | gps_height   | longitude   | latitude   | num_private   | region_code   | district_code   | population   | construction_year   |
|:------|:--------|:-------------|:-------------|:------------|:-----------|:--------------|:--------------|:----------------|:-------------|:--------------------|
| count | 59400   | 59400        | 59400        | 59400       | 59400      | 59400         | 59400         | 59400           | 59400        | 59400               |
| mean  | 37115.1 | 317.65       | 668.297      | 34.0774     | -5.70603   | 0.474141      | 15.297        | 5.62975         | 179.91       | 1300.65             |
| std   | 21453.1 | 2997.57      | 693.116      | 6.56743     | 2.94602    | 12.2362       | 17.5874       | 9.63365         | 471.482      | 951.621             |
| min   | 0       | 0            | -90          | 0           | -11.6494   | 0             | 1             | 0               | 0            | 0                   |
| 25%   | 18519.8 | 0            | 0            | 33.0903     | -8.54062   | 0             | 5             | 2               | 0            | 0                   |
| 50%   | 37061.5 | 0            | 369          | 34.9087     | -5.0216    | 0             | 12            | 3               | 25           | 1986                |
| 75%   | 55656.5 | 20           | 1319.25      | 37.1784     | -3.32616   | 0             | 17            | 5               | 215          | 2004                |
| max   | 74247   | 350000       | 2770         | 40.3452     | -2e-08     | 1776          | 99            | 80              | 30500        | 2013                |

Number of Duplicate Rows: 0

Number of Unique Values per Column:
|                       | 0     |
|:----------------------|:------|
| id                    | 59400 |
| amount_tsh            | 98    |
| date_recorded         | 356   |
| funder                | 1896  |
| gps_height            | 2428  |
| installer             | 2145  |
| longitude             | 57516 |
| latitude              | 57517 |
| wpt_name              | 37399 |
| num_private           | 65    |
| basin                 | 9     |
| subvillage            | 19287 |
| region                | 21    |
| region_code           | 27    |
| district_code         | 20    |
| lga                   | 125   |
| ward                  | 2092  |
| population            | 1049  |
| public_meeting        | 2     |
| recorded_by           | 1     |
| scheme_management     | 11    |
| scheme_name           | 2695  |
| permit                | 2     |
| construction_year     | 55    |
| extraction_type       | 18    |
| extraction_type_group | 13    |
| extraction_type_class | 7     |
| management            | 12    |
| management_group      | 5     |
| payment               | 7     |
| payment_type          | 7     |
| water_quality         | 8     |
| quality_group         | 6     |
| quantity              | 5     |
| quantity_group        | 5     |
| source                | 10    |
| source_type           | 7     |
| source_class          | 3     |
| waterpoint_type       | 7     |
| waterpoint_type_group | 6     |
| status_group          | 3     |

Percentage of Missing/Null Values per Column:
|                       | 0    |
|:----------------------|:-----|
| id                    | 0    |
| amount_tsh            | 0    |
| date_recorded         | 0    |
| funder                | 6.12 |
| gps_height            | 0    |
| installer             | 6.15 |
| longitude             | 0    |
| latitude              | 0    |
| wpt_name              | 0    |
| num_private           | 0    |
| basin                 | 0    |
| subvillage            | 0.62 |
| region                | 0    |
| region_code           | 0    |
| district_code         | 0    |
| lga                   | 0    |
| ward                  | 0    |
| population            | 0    |
| public_meeting        | 5.61 |
| recorded_by           | 0    |
| scheme_management     | 6.53 |
| scheme_name           | 48.5 |
| permit                | 5.14 |
| construction_year     | 0    |
| extraction_type       | 0    |
| extraction_type_group | 0    |
| extraction_type_class | 0    |
| management            | 0    |
| management_group      | 0    |
| payment               | 0    |
| payment_type          | 0    |
| water_quality         | 0    |
| quality_group         | 0    |
| quantity              | 0    |
| quantity_group        | 0    |
| source                | 0    |
| source_type           | 0    |
| source_class          | 0    |
| waterpoint_type       | 0    |
| waterpoint_type_group | 0    |
| status_group          | 0    |

In [7]:
overview.show_overview(test_data, "Test Set")

--- Overview of Test Set ---

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14850 entries, 0 to 14849
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     14850 non-null  int64
 1   amount_tsh             14850 non-null  float64
 2   date_recorded          14850 non-null  object
 3   funder                 13980 non-null  object
 4   gps_height             14850 non-null  int64
 5   installer              13973 non-null  object
 6   longitude              14850 non-null  float64
 7   latitude               14850 non-null  float64
 8   wpt_name               14850 non-null  object
 9   num_private            14850 non-null  int64
 10  basin                  14850 non-null  object
 11  subvillage             14751 non-null  object
 12  region                 14850 non-null  object
 13  region_code            14850 non-null  int64
 14  district_code          14850 non-null  int64
 15  lga                    14850 non-null  object
 16  ward                   14850 non-null  object
 17  population             14850 non-null  int64
 18  public_meeting         14029 non-null  object
 19  recorded_by            14850 non-null  object
 20  scheme_management      13881 non-null  object
 21  scheme_name            7608 non-null   object
 22  permit                 14113 non-null  object
 23  construction_year      14850 non-null  int64
 24  extraction_type        14850 non-null  object
 25  extraction_type_group  14850 non-null  object
 26  extraction_type_class  14850 non-null  object
 27  management             14850 non-null  object
 28  management_group       14850 non-null  object
 29  payment                14850 non-null  object
 30  payment_type           14850 non-null  object
 31  water_quality          14850 non-null  object
 32  quality_group          14850 non-null  object
 33  quantity               14850 non-null  object
 34  quantity_group         14850 non-null  object
 35  source                 14850 non-null  object
 36  source_type            14850 non-null  object
 37  source_class           14850 non-null  object
 38  waterpoint_type        14850 non-null  object
 39  waterpoint_type_group  14850 non-null  object
dtypes: float64(3), int64(7), object(30)
memory usage: 4.5+ MB
None

First 5 Rows:
| id    | amount_tsh   | date_recorded   | funder                 | gps_height   | installer   | longitude   | latitude   | wpt_name                | num_private   | basin                   | subvillage   | region   | region_code   | district_code   | lga           | ward         | population   | public_meeting   | recorded_by             | scheme_management   | scheme_name    | permit   | construction_year   | extraction_type   | extraction_type_group   | extraction_type_class   | management   | management_group   | payment     | payment_type   | water_quality   | quality_group   | quantity     | quantity_group   | source               | source_type          | source_class   | waterpoint_type    | waterpoint_type_group   |
|:------|:-------------|:----------------|:-----------------------|:-------------|:------------|:------------|:-----------|:------------------------|:--------------|:------------------------|:-------------|:---------|:--------------|:----------------|:--------------|:-------------|:-------------|:-----------------|:------------------------|:--------------------|:---------------|:---------|:--------------------|:------------------|:------------------------|:------------------------|:-------------|:-------------------|:------------|:---------------|:----------------|:----------------|:-------------|:-----------------|:---------------------|:---------------------|:---------------|:-------------------|:------------------------|
| 50785 | 0            | 2013-02-04      | Dmdd                   | 1996         | DMDD        | 35.2908     | -4.0597    | Dinamu Secondary School | 0             | Internal                | Magoma       | Manyara  | 21            | 3               | Mbulu         | Bashay       | 321          | 1                | GeoData Consultants Ltd | Parastatal          | nan            | 1        | 2012                | other             | other                   | other                   | parastatal   | parastatal         | never pay   | never pay      | soft            | good            | seasonal     | seasonal         | rainwater harvesting | rainwater harvesting | surface        | other              | other                   |
| 51630 | 0            | 2013-02-04      | Government Of Tanzania | 1569         | DWE         | 36.6567     | -3.30921   | Kimnyak                 | 0             | Pangani                 | Kimnyak      | Arusha   | 2             | 2               | Arusha Rural  | Kimnyaki     | 300          | 1                | GeoData Consultants Ltd | VWC                 | TPRI pipe line | 1        | 2000                | gravity           | gravity                 | gravity                 | vwc          | user-group         | never pay   | never pay      | soft            | good            | insufficient | insufficient     | spring               | spring               | groundwater    | communal standpipe | communal standpipe      |
| 17168 | 0            | 2013-02-01      | nan                    | 1567         | nan         | 34.7679     | -5.00434   | Puma Secondary          | 0             | Internal                | Msatu        | Singida  | 13            | 2               | Singida Rural | Puma         | 500          | 1                | GeoData Consultants Ltd | VWC                 | P              | nan      | 2010                | other             | other                   | other                   | vwc          | user-group         | never pay   | never pay      | soft            | good            | insufficient | insufficient     | rainwater harvesting | rainwater harvesting | surface        | other              | other                   |
| 45559 | 0            | 2013-01-22      | Finn Water             | 267          | FINN WATER  | 38.058      | -9.41867   | Kwa Mzee Pange          | 0             | Ruvuma / Southern Coast | Kipindimbi   | Lindi    | 80            | 43              | Liwale        | Mkutano      | 250          | nan              | GeoData Consultants Ltd | VWC                 | nan            | 1        | 1987                | other             | other                   | other                   | vwc          | user-group         | unknown     | unknown        | soft            | good            | dry          | dry              | shallow well         | shallow well         | groundwater    | other              | other                   |
| 49871 | 500          | 2013-03-27      | Bruder                 | 1260         | BRUDER      | 35.0061     | -10.9504   | Kwa Mzee Turuka         | 0             | Ruvuma / Southern Coast | Losonga      | Ruvuma   | 10            | 3               | Mbinga        | Mbinga Urban | 60           | nan              | GeoData Consultants Ltd | Water Board         | BRUDER         | 1        | 2000                | gravity           | gravity                 | gravity                 | water board  | user-group         | pay monthly | monthly        | soft            | good            | enough       | enough           | spring               | spring               | groundwater    | communal standpipe | communal standpipe      |

Last 5 Rows:
| id    | amount_tsh   | date_recorded   | funder                 | gps_height   | installer   | longitude   | latitude   | wpt_name         | num_private   | basin       | subvillage   | region   | region_code   | district_code   | lga           | ward       | population   | public_meeting   | recorded_by             | scheme_management   | scheme_name               | permit   | construction_year   | extraction_type   | extraction_type_group   | extraction_type_class   | management   | management_group   | payment      | payment_type   | water_quality   | quality_group   | quantity     | quantity_group   | source       | source_type   | source_class   | waterpoint_type    | waterpoint_type_group   |
|:------|:-------------|:----------------|:-----------------------|:-------------|:------------|:------------|:-----------|:-----------------|:--------------|:------------|:-------------|:---------|:--------------|:----------------|:--------------|:-----------|:-------------|:-----------------|:------------------------|:--------------------|:--------------------------|:---------|:--------------------|:------------------|:------------------------|:------------------------|:-------------|:-------------------|:-------------|:---------------|:----------------|:----------------|:-------------|:-----------------|:-------------|:--------------|:---------------|:-------------------|:------------------------|
| 39307 | 0            | 2011-02-24      | Danida                 | 34           | Da          | 38.8527     | -6.58284   | Kwambwezi        | 0             | Wami / Ruvu | Yombo        | Pwani    | 6             | 1               | Bagamoyo      | Yombo      | 20           | True             | GeoData Consultants Ltd | VWC                 | Bagamoyo wate             | 1        | 1988                | mono              | mono                    | motorpump               | vwc          | user-group         | never pay    | never pay      | soft            | good            | enough       | enough           | river        | river/lake    | surface        | communal standpipe | communal standpipe      |
| 18990 | 1000         | 2011-03-21      | Hiap                   | 0            | HIAP        | 37.4516     | -5.35043   | Bonde La Mkondoa | 0             | Pangani     | Mkondoa      | Tanga    | 4             | 7               | Kilindi       | Mvungwe    | 2960         | True             | GeoData Consultants Ltd | VWC                 | nan                       | 0        | 1994                | nira/tanira       | nira/tanira             | handpump                | vwc          | user-group         | pay annually | annually       | salty           | salty           | insufficient | insufficient     | shallow well | shallow well  | groundwater    | hand pump          | hand pump               |
| 28749 | 0            | 2013-03-04      | nan                    | 1476         | nan         | 34.7398     | -4.58559   | Bwawani          | 0             | Internal    | Juhudi       | Singida  | 13            | 2               | Singida Rural | Ughandi    | 200          | True             | GeoData Consultants Ltd | VWC                 | nan                       | nan      | 2010                | gravity           | gravity                 | gravity                 | vwc          | user-group         | never pay    | never pay      | soft            | good            | insufficient | insufficient     | dam          | dam           | surface        | communal standpipe | communal standpipe      |
| 33492 | 0            | 2013-02-18      | Germany                | 998          | DWE         | 35.4327     | -10.5842   | Kwa John         | 0             | Lake Nyasa  | Namakinga B  | Ruvuma   | 10            | 2               | Songea Rural  | Maposeni   | 150          | True             | GeoData Consultants Ltd | VWC                 | Mradi wa maji wa maposeni | 1        | 2009                | gravity           | gravity                 | gravity                 | vwc          | user-group         | never pay    | never pay      | soft            | good            | insufficient | insufficient     | river        | river/lake    | surface        | communal standpipe | communal standpipe      |
| 68707 | 0            | 2013-02-13      | Government Of Tanzania | 481          | Government  | 34.7651     | -11.226    | Kwa Mzee Chagala | 0             | Lake Nyasa  | Kamba        | Ruvuma   | 10            | 3               | Mbinga        | Mbamba bay | 40           | True             | GeoData Consultants Ltd | VWC                 | DANIDA                    | 1        | 2008                | gravity           | gravity                 | gravity                 | vwc          | user-group         | never pay    | never pay      | soft            | good            | dry          | dry              | spring       | spring        | groundwater    | communal standpipe | communal standpipe      |

Descriptive Statistics:
|       | id      | amount_tsh   | gps_height   | longitude   | latitude   | num_private   | region_code   | district_code   | population   | construction_year   |
|:------|:--------|:-------------|:-------------|:------------|:-----------|:--------------|:--------------|:----------------|:-------------|:--------------------|
| count | 14850   | 14850        | 14850        | 14850       | 14850      | 14850         | 14850         | 14850           | 14850        | 14850               |
| mean  | 37162   | 322.827      | 655.148      | 34.0616     | -5.68472   | 0.415084      | 15.1391       | 5.6264          | 184.114      | 1289.71             |
| std   | 21359.4 | 2510.97      | 691.261      | 6.59303     | 2.9408     | 8.16791       | 17.1913       | 9.67384         | 469.499      | 955.241             |
| min   | 10      | 0            | -57          | 0           | -11.5646   | 0             | 1             | 0               | 0            | 0                   |
| 25%   | 18727   | 0            | 0            | 33.0695     | -8.44397   | 0             | 5             | 2               | 0            | 0                   |
| 50%   | 37361.5 | 0            | 344          | 34.9012     | -5.04975   | 0             | 12            | 3               | 20           | 1986                |
| 75%   | 55799.8 | 25           | 1308         | 37.1966     | -3.32059   | 0             | 17            | 5               | 220          | 2004                |
| max   | 74249   | 200000       | 2777         | 40.325      | -2e-08     | 669           | 99            | 80              | 11469        | 2013                |

Number of Duplicate Rows: 0

Number of Unique Values per Column:
|                       | 0     |
|:----------------------|:------|
| id                    | 14850 |
| amount_tsh            | 68    |
| date_recorded         | 331   |
| funder                | 979   |
| gps_height            | 2157  |
| installer             | 1091  |
| longitude             | 14390 |
| latitude              | 14390 |
| wpt_name              | 10840 |
| num_private           | 36    |
| basin                 | 9     |
| subvillage            | 8443  |
| region                | 21    |
| region_code           | 26    |
| district_code         | 20    |
| lga                   | 125   |
| ward                  | 1959  |
| population            | 637   |
| public_meeting        | 2     |
| recorded_by           | 1     |
| scheme_management     | 11    |
| scheme_name           | 1788  |
| permit                | 2     |
| construction_year     | 55    |
| extraction_type       | 17    |
| extraction_type_group | 13    |
| extraction_type_class | 7     |
| management            | 12    |
| management_group      | 5     |
| payment               | 7     |
| payment_type          | 7     |
| water_quality         | 8     |
| quality_group         | 6     |
| quantity              | 5     |
| quantity_group        | 5     |
| source                | 10    |
| source_type           | 7     |
| source_class          | 3     |
| waterpoint_type       | 7     |
| waterpoint_type_group | 6     |

Percentage of Missing/Null Values per Column:
|                       | 0     |
|:----------------------|:------|
| id                    | 0     |
| amount_tsh            | 0     |
| date_recorded         | 0     |
| funder                | 5.86  |
| gps_height            | 0     |
| installer             | 5.91  |
| longitude             | 0     |
| latitude              | 0     |
| wpt_name              | 0     |
| num_private           | 0     |
| basin                 | 0     |
| subvillage            | 0.67  |
| region                | 0     |
| region_code           | 0     |
| district_code         | 0     |
| lga                   | 0     |
| ward                  | 0     |
| population            | 0     |
| public_meeting        | 5.53  |
| recorded_by           | 0     |
| scheme_management     | 6.53  |
| scheme_name           | 48.77 |
| permit                | 4.96  |
| construction_year     | 0     |
| extraction_type       | 0     |
| extraction_type_group | 0     |
| extraction_type_class | 0     |
| management            | 0     |
| management_group      | 0     |
| payment               | 0     |
| payment_type          | 0     |
| water_quality         | 0     |
| quality_group         | 0     |
| quantity              | 0     |
| quantity_group        | 0     |
| source                | 0     |
| source_type           | 0     |
| source_class          | 0     |
| waterpoint_type       | 0     |
| waterpoint_type_group | 0     |

## __2.4 Data Cleaning__

The `DataCleaning` class, an extension of `DataOverview`, executes data cleaning operations on both training and test datasets while providing comprehensive overviews of both the original and cleaned versions. It conducts operations such as extracting the year from the recorded date, imputing missing and zero values, dropping irrelevant columns, and ultimately saving the cleaned datasets with detailed overviews.

In [8]:
class DataCleaning(DataOverview):  
    """
    Cleans the training and test datasets, handling zeros/none/unknown values as missing and providing overviews.
    """

    def clean_data(self, df, dataset_name="Dataset"):
        """
        Performs cleaning operations on the DataFrame and saves the results.

        Args:
            df (DataFrame): The DataFrame to clean.
            dataset_name (str): The name of the dataset for saving.
        """
        print(f"\n--- Cleaning {dataset_name} Set ---\n")

        # Feature Engineering
        df["year_recorded"] = pd.to_datetime(df["date_recorded"]).dt.year
        df.drop(columns=["date_recorded"], inplace=True)

        # Handle specific values as missing
        df["longitude"] = df["longitude"].replace(0.0, pd.NA)
        df["wpt_name"] = df["wpt_name"].replace("none", pd.NA)

        # Impute "unknown" in categorical columns
        categorical_cols = df.select_dtypes(include=['object']).columns
        for col in categorical_cols:
            df[col] = df[col].replace("unknown", pd.NA)  # Treat "unknown" as missing
            most_frequent_value = df[col].mode()[0]   # Find most frequent value
            df[col] = df[col].fillna(most_frequent_value)  # Impute with mode

        # Handle zeros as missing values (excluding 'amount_tsh' and 'longitude')
        for col in df.select_dtypes(include=['int64', 'float64']):
            if col not in ["amount_tsh", "longitude"]:
                zero_proportion = (df[col] == 0).mean()
                if zero_proportion > 0.30:
                    df[col] = df[col].replace(0, pd.NA)
                    df[col] = df[col].fillna(df[col].median())

        # Drop columns
        df.drop(columns=["num_private", "recorded_by", "scheme_name",
                         "extraction_type_group", "extraction_type", "payment",
                         "water_quality", "quantity_group", "source", "source_type",
                         "waterpoint_type_group", "management", "lga", "ward"], inplace=True)

        # Save cleaned data and show overview
        file_path = f"data/cleaned_{dataset_name.lower()}_set.csv"
        df.to_csv(file_path, index=False)
        print(f"Cleaned {dataset_name} set saved to {file_path}")

        self.show_overview(df, f"Cleaned {dataset_name} Set")

        return df



cleaner = DataCleaning()
train_data, test_data = cleaner.load_data()

# Show overviews before cleaning
# cleaner.show_overview(train_data, "Original Training Set")
# cleaner.show_overview(test_data, "Original Test Set")

cleaned_train_data = cleaner.clean_data(train_data, "Training")
cleaned_test_data = cleaner.clean_data(test_data, "Test")

--- Cleaning Training Set ---

C:\Users\tonyg\AppData\Local\Temp\ipykernel_3016\835964918.py:29: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(most_frequent_value)  # Impute with mode
C:\Users\tonyg\AppData\Local\Temp\ipykernel_3016\835964918.py:37: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].median())
C:\Users\tonyg\AppData\Local\Temp\ipykernel_3016\835964918.py:37: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].median())
C:\Users\tonyg\AppData\Local\Temp\ipykernel_3016\835964918.py:37: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].median())
C:\Users\tonyg\AppData\Local\Temp\ipykernel_3016\835964918.py:37: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].median())

Cleaned Training set saved to data/cleaned_training_set.csv

--- Overview of Cleaned Training Set ---

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   amount_tsh             59400 non-null  float64
 2   funder                 59400 non-null  object
 3   gps_height             59400 non-null  float64
 4   installer              59400 non-null  object
 5   longitude              59400 non-null  float64
 6   latitude               59400 non-null  float64
 7   wpt_name               59400 non-null  object
 8   basin                  59400 non-null  object
 9   subvillage             59400 non-null  object
 10  region                 59400 non-null  object
 11  region_code            59400 non-null  int64
 12  district_code          59400 non-null  int64
 13  population             59400 non-null  float64
 14  public_meeting         59400 non-null  bool
 15  scheme_management      59400 non-null  object
 16  permit                 59400 non-null  bool
 17  construction_year      59400 non-null  float64
 18  extraction_type_class  59400 non-null  object
 19  management_group       59400 non-null  object
 20  payment_type           59400 non-null  object
 21  quality_group          59400 non-null  object
 22  quantity               59400 non-null  object
 23  source_class           59400 non-null  object
 24  waterpoint_type        59400 non-null  object
 25  status_group           59400 non-null  object
 26  year_recorded          59400 non-null  int32
dtypes: bool(2), float64(6), int32(1), int64(3), object(15)
memory usage: 11.2+ MB
None

First 5 Rows:
| id    | amount_tsh   | funder       | gps_height   | installer    | longitude   | latitude   | wpt_name             | basin                   | subvillage   | region   | region_code   | district_code   | population   | public_meeting   | scheme_management   | permit   | construction_year   | extraction_type_class   | management_group   | payment_type   | quality_group   | quantity     | source_class   | waterpoint_type             | status_group   | year_recorded   |
|:------|:-------------|:-------------|:-------------|:-------------|:------------|:-----------|:---------------------|:------------------------|:-------------|:---------|:--------------|:----------------|:-------------|:-----------------|:--------------------|:---------|:--------------------|:------------------------|:-------------------|:---------------|:----------------|:-------------|:---------------|:----------------------------|:---------------|:----------------|
| 69572 | 6000         | Roman        | 1390         | Roman        | 34.9381     | -9.85632   | Shuleni              | Lake Nyasa              | Mnyusi B     | Iringa   | 11            | 5               | 109          | True             | VWC                 | False    | 1999                | gravity                 | user-group         | annually       | good            | enough       | groundwater    | communal standpipe          | functional     | 2011            |
| 8776  | 0            | Grumeti      | 1399         | GRUMETI      | 34.6988     | -2.14747   | Zahanati             | Lake Victoria           | Nyamara      | Mara     | 20            | 2               | 280          | True             | Other               | True     | 2010                | gravity                 | user-group         | never pay      | good            | insufficient | surface        | communal standpipe          | functional     | 2013            |
| 34310 | 25           | Lottery Club | 686          | World vision | 37.4607     | -3.82133   | Kwa Mahundi          | Pangani                 | Majengo      | Manyara  | 21            | 4               | 250          | True             | VWC                 | True     | 2009                | gravity                 | user-group         | per bucket     | good            | enough       | surface        | communal standpipe multiple | functional     | 2013            |
| 67743 | 0            | Unicef       | 263          | UNICEF       | 38.4862     | -11.1553   | Zahanati Ya Nanyumbu | Ruvuma / Southern Coast | Mahakamani   | Mtwara   | 90            | 63              | 58           | True             | VWC                 | True     | 1986                | submersible             | user-group         | never pay      | good            | dry          | groundwater    | communal standpipe multiple | non functional | 2013            |
| 19728 | 0            | Action In A  | 1167         | Artisan      | 31.1308     | -1.82536   | Shuleni              | Lake Victoria           | Kyanyamisa   | Kagera   | 18            | 1               | 150          | True             | VWC                 | True     | 2000                | gravity                 | other              | never pay      | good            | seasonal     | surface        | communal standpipe          | functional     | 2011            |

Last 5 Rows:
| id    | amount_tsh   | funder                 | gps_height   | installer   | longitude   | latitude   | wpt_name            | basin       | subvillage   | region      | region_code   | district_code   | population   | public_meeting   | scheme_management   | permit   | construction_year   | extraction_type_class   | management_group   | payment_type   | quality_group   | quantity     | source_class   | waterpoint_type    | status_group   | year_recorded   |
|:------|:-------------|:-----------------------|:-------------|:------------|:------------|:-----------|:--------------------|:------------|:-------------|:------------|:--------------|:----------------|:-------------|:-----------------|:--------------------|:---------|:--------------------|:------------------------|:-------------------|:---------------|:----------------|:-------------|:---------------|:-------------------|:---------------|:----------------|
| 60739 | 10           | Germany Republi        | 1210         | CES         | 37.1698     | -3.25385   | Area Three Namba 27 | Pangani     | Kiduruni     | Kilimanjaro | 3             | 5               | 125          | True             | Water Board         | True     | 1999                | gravity                 | user-group         | per bucket     | good            | enough       | groundwater    | communal standpipe | functional     | 2013            |
| 27263 | 4700         | Cefa-njombe            | 1212         | Cefa        | 35.25       | -9.07063   | Kwa Yahona Kuvala   | Rufiji      | Igumbilo     | Iringa      | 11            | 4               | 56           | True             | VWC                 | True     | 1996                | gravity                 | user-group         | annually       | good            | enough       | surface        | communal standpipe | functional     | 2011            |
| 37057 | 0            | Government Of Tanzania | 1167         | DWE         | 34.0171     | -8.75043   | Mashine             | Rufiji      | Madungulu    | Mbeya       | 12            | 7               | 150          | True             | VWC                 | False    | 2000                | handpump                | user-group         | monthly        | fluoride        | enough       | groundwater    | hand pump          | functional     | 2011            |
| 31282 | 0            | Malec                  | 1167         | Musa        | 35.8613     | -6.37857   | Mshoro              | Rufiji      | Mwinyi       | Dodoma      | 1             | 4               | 150          | True             | VWC                 | True     | 2000                | handpump                | user-group         | never pay      | good            | insufficient | groundwater    | hand pump          | functional     | 2011            |
| 26348 | 0            | World Bank             | 191          | World       | 38.104      | -6.74746   | Kwa Mzee Lugawa     | Wami / Ruvu | Kikatanyemba | Morogoro    | 5             | 2               | 150          | True             | VWC                 | True     | 2002                | handpump                | user-group         | on failure     | salty           | enough       | groundwater    | hand pump          | functional     | 2011            |

Descriptive Statistics:
|       | id      | amount_tsh   | gps_height   | longitude   | latitude   | region_code   | district_code   | population   | construction_year   | year_recorded   |
|:------|:--------|:-------------|:-------------|:------------|:-----------|:--------------|:----------------|:-------------|:--------------------|:----------------|
| count | 59400   | 59400        | 59400        | 59400       | 59400      | 59400         | 59400           | 59400        | 59400               | 59400           |
| mean  | 37115.1 | 317.65       | 1069.83      | 35.042      | -5.70603   | 15.297        | 5.62975         | 233.902      | 1997.93             | 2011.92         |
| std   | 21453.1 | 2997.57      | 501.077      | 2.63815     | 2.94602    | 17.5874       | 9.63365         | 456.126      | 10.1796             | 0.958758        |
| min   | 0       | 0            | -90          | 29.6071     | -11.6494   | 1             | 0               | 1            | 1960                | 2002            |
| 25%   | 18519.8 | 0            | 903          | 33.0903     | -8.54062   | 5             | 2               | 100          | 1996                | 2011            |
| 50%   | 37061.5 | 0            | 1167         | 34.9087     | -5.0216    | 12            | 3               | 150          | 2000                | 2012            |
| 75%   | 55656.5 | 20           | 1319.25      | 37.1784     | -3.32616   | 17            | 5               | 215          | 2004                | 2013            |
| max   | 74247   | 350000       | 2770         | 40.3452     | -2e-08     | 99            | 80              | 30500        | 2013                | 2013            |

Number of Duplicate Rows: 0

Number of Unique Values per Column:
|                       | 0     |
|:----------------------|:------|
| id                    | 59400 |
| amount_tsh            | 98    |
| funder                | 1896  |
| gps_height            | 2427  |
| installer             | 2144  |
| longitude             | 57515 |
| latitude              | 57517 |
| wpt_name              | 37398 |
| basin                 | 9     |
| subvillage            | 19287 |
| region                | 21    |
| region_code           | 27    |
| district_code         | 20    |
| population            | 1048  |
| public_meeting        | 2     |
| scheme_management     | 11    |
| permit                | 2     |
| construction_year     | 54    |
| extraction_type_class | 7     |
| management_group      | 4     |
| payment_type          | 6     |
| quality_group         | 5     |
| quantity              | 4     |
| source_class          | 2     |
| waterpoint_type       | 7     |
| status_group          | 3     |
| year_recorded         | 5     |

Percentage of Missing/Null Values per Column:
|                       | 0   |
|:----------------------|:----|
| id                    | 0   |
| amount_tsh            | 0   |
| funder                | 0   |
| gps_height            | 0   |
| installer             | 0   |
| longitude             | 0   |
| latitude              | 0   |
| wpt_name              | 0   |
| basin                 | 0   |
| subvillage            | 0   |
| region                | 0   |
| region_code           | 0   |
| district_code         | 0   |
| population            | 0   |
| public_meeting        | 0   |
| scheme_management     | 0   |
| permit                | 0   |
| construction_year     | 0   |
| extraction_type_class | 0   |
| management_group      | 0   |
| payment_type          | 0   |
| quality_group         | 0   |
| quantity              | 0   |
| source_class          | 0   |
| waterpoint_type       | 0   |
| status_group          | 0   |
| year_recorded         | 0   |

--- Cleaning Test Set ---

C:\Users\tonyg\AppData\Local\Temp\ipykernel_3016\835964918.py:29: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(most_frequent_value)  # Impute with mode
C:\Users\tonyg\AppData\Local\Temp\ipykernel_3016\835964918.py:37: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].median())
C:\Users\tonyg\AppData\Local\Temp\ipykernel_3016\835964918.py:37: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].median())
C:\Users\tonyg\AppData\Local\Temp\ipykernel_3016\835964918.py:37: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].median())
C:\Users\tonyg\AppData\Local\Temp\ipykernel_3016\835964918.py:37: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].median())

Cleaned Test set saved to data/cleaned_test_set.csv

--- Overview of Cleaned Test Set ---

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14850 entries, 0 to 14849
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     14850 non-null  int64
 1   amount_tsh             14850 non-null  float64
 2   funder                 14850 non-null  object
 3   gps_height             14850 non-null  float64
 4   installer              14850 non-null  object
 5   longitude              14850 non-null  float64
 6   latitude               14850 non-null  float64
 7   wpt_name               14850 non-null  object
 8   basin                  14850 non-null  object
 9   subvillage             14850 non-null  object
 10  region                 14850 non-null  object
 11  region_code            14850 non-null  int64
 12  district_code          14850 non-null  int64
 13  population             14850 non-null  float64
 14  public_meeting         14850 non-null  bool
 15  scheme_management      14850 non-null  object
 16  permit                 14850 non-null  bool
 17  construction_year      14850 non-null  float64
 18  extraction_type_class  14850 non-null  object
 19  management_group       14850 non-null  object
 20  payment_type           14850 non-null  object
 21  quality_group          14850 non-null  object
 22  quantity               14850 non-null  object
 23  source_class           14850 non-null  object
 24  waterpoint_type        14850 non-null  object
 25  year_recorded          14850 non-null  int32
dtypes: bool(2), float64(6), int32(1), int64(3), object(14)
memory usage: 2.7+ MB
None

First 5 Rows:
| id    | amount_tsh   | funder                 | gps_height   | installer   | longitude   | latitude   | wpt_name                | basin                   | subvillage   | region   | region_code   | district_code   | population   | public_meeting   | scheme_management   | permit   | construction_year   | extraction_type_class   | management_group   | payment_type   | quality_group   | quantity     | source_class   | waterpoint_type    | year_recorded   |
|:------|:-------------|:-----------------------|:-------------|:------------|:------------|:-----------|:------------------------|:------------------------|:-------------|:---------|:--------------|:----------------|:-------------|:-----------------|:--------------------|:---------|:--------------------|:------------------------|:-------------------|:---------------|:----------------|:-------------|:---------------|:-------------------|:----------------|
| 50785 | 0            | Dmdd                   | 1996         | DMDD        | 35.2908     | -4.0597    | Dinamu Secondary School | Internal                | Magoma       | Manyara  | 21            | 3               | 321          | True             | Parastatal          | True     | 2012                | other                   | parastatal         | never pay      | good            | seasonal     | surface        | other              | 2013            |
| 51630 | 0            | Government Of Tanzania | 1569         | DWE         | 36.6567     | -3.30921   | Kimnyak                 | Pangani                 | Kimnyak      | Arusha   | 2             | 2               | 300          | True             | VWC                 | True     | 2000                | gravity                 | user-group         | never pay      | good            | insufficient | groundwater    | communal standpipe | 2013            |
| 17168 | 0            | Government Of Tanzania | 1567         | DWE         | 34.7679     | -5.00434   | Puma Secondary          | Internal                | Msatu        | Singida  | 13            | 2               | 500          | True             | VWC                 | True     | 2010                | other                   | user-group         | never pay      | good            | insufficient | surface        | other              | 2013            |
| 45559 | 0            | Finn Water             | 267          | FINN WATER  | 38.058      | -9.41867   | Kwa Mzee Pange          | Ruvuma / Southern Coast | Kipindimbi   | Lindi    | 80            | 43              | 250          | True             | VWC                 | True     | 1987                | other                   | user-group         | never pay      | good            | dry          | groundwater    | other              | 2013            |
| 49871 | 500          | Bruder                 | 1260         | BRUDER      | 35.0061     | -10.9504   | Kwa Mzee Turuka         | Ruvuma / Southern Coast | Losonga      | Ruvuma   | 10            | 3               | 60           | True             | Water Board         | True     | 2000                | gravity                 | user-group         | monthly        | good            | enough       | groundwater    | communal standpipe | 2013            |

Last 5 Rows:
| id    | amount_tsh   | funder                 | gps_height   | installer   | longitude   | latitude   | wpt_name         | basin       | subvillage   | region   | region_code   | district_code   | population   | public_meeting   | scheme_management   | permit   | construction_year   | extraction_type_class   | management_group   | payment_type   | quality_group   | quantity     | source_class   | waterpoint_type    | year_recorded   |
|:------|:-------------|:-----------------------|:-------------|:------------|:------------|:-----------|:-----------------|:------------|:-------------|:---------|:--------------|:----------------|:-------------|:-----------------|:--------------------|:---------|:--------------------|:------------------------|:-------------------|:---------------|:----------------|:-------------|:---------------|:-------------------|:----------------|
| 39307 | 0            | Danida                 | 34           | Da          | 38.8527     | -6.58284   | Kwambwezi        | Wami / Ruvu | Yombo        | Pwani    | 6             | 1               | 20           | True             | VWC                 | True     | 1988                | motorpump               | user-group         | never pay      | good            | enough       | surface        | communal standpipe | 2011            |
| 18990 | 1000         | Hiap                   | 1165         | HIAP        | 37.4516     | -5.35043   | Bonde La Mkondoa | Pangani     | Mkondoa      | Tanga    | 4             | 7               | 2960         | True             | VWC                 | False    | 1994                | handpump                | user-group         | annually       | salty           | insufficient | groundwater    | hand pump          | 2011            |
| 28749 | 0            | Government Of Tanzania | 1476         | DWE         | 34.7398     | -4.58559   | Bwawani          | Internal    | Juhudi       | Singida  | 13            | 2               | 200          | True             | VWC                 | True     | 2010                | gravity                 | user-group         | never pay      | good            | insufficient | surface        | communal standpipe | 2013            |
| 33492 | 0            | Germany                | 998          | DWE         | 35.4327     | -10.5842   | Kwa John         | Lake Nyasa  | Namakinga B  | Ruvuma   | 10            | 2               | 150          | True             | VWC                 | True     | 2009                | gravity                 | user-group         | never pay      | good            | insufficient | surface        | communal standpipe | 2013            |
| 68707 | 0            | Government Of Tanzania | 481          | Government  | 34.7651     | -11.226    | Kwa Mzee Chagala | Lake Nyasa  | Kamba        | Ruvuma   | 10            | 3               | 40           | True             | VWC                 | True     | 2008                | gravity                 | user-group         | never pay      | good            | dry          | groundwater    | communal standpipe | 2013            |

Descriptive Statistics:
|       | id      | amount_tsh   | gps_height   | longitude   | latitude   | region_code   | district_code   | population   | construction_year   | year_recorded   |
|:------|:--------|:-------------|:-------------|:------------|:-----------|:--------------|:----------------|:-------------|:--------------------|:----------------|
| count | 14850   | 14850        | 14850        | 14850       | 14850      | 14850         | 14850           | 14850        | 14850               | 14850           |
| mean  | 37162   | 322.827      | 1063.96      | 35.0747     | -5.68472   | 15.1391       | 5.6264          | 239.195      | 1998.13             | 2011.91         |
| std   | 21359.4 | 2510.97      | 501.302      | 2.60289     | 2.9408     | 17.1913       | 9.67384         | 453.183      | 9.98963             | 0.966373        |
| min   | 10      | 0            | -57          | 29.6128     | -11.5646   | 1             | 0               | 1            | 1960                | 2001            |
| 25%   | 18727   | 0            | 881          | 33.0695     | -8.44397   | 5             | 2               | 100          | 1996                | 2011            |
| 50%   | 37361.5 | 0            | 1165         | 34.9012     | -5.04975   | 12            | 3               | 150          | 2000                | 2012            |
| 75%   | 55799.8 | 25           | 1308         | 37.1966     | -3.32059   | 17            | 5               | 220          | 2004                | 2013            |
| max   | 74249   | 200000       | 2777         | 40.325      | -2e-08     | 99            | 80              | 11469        | 2013                | 2013            |

Number of Duplicate Rows: 0

Number of Unique Values per Column:
|                       | 0     |
|:----------------------|:------|
| id                    | 14850 |
| amount_tsh            | 68    |
| funder                | 979   |
| gps_height            | 2156  |
| installer             | 1091  |
| longitude             | 14389 |
| latitude              | 14390 |
| wpt_name              | 10839 |
| basin                 | 9     |
| subvillage            | 8443  |
| region                | 21    |
| region_code           | 26    |
| district_code         | 20    |
| population            | 636   |
| public_meeting        | 2     |
| scheme_management     | 11    |
| permit                | 2     |
| construction_year     | 54    |
| extraction_type_class | 7     |
| management_group      | 4     |
| payment_type          | 6     |
| quality_group         | 5     |
| quantity              | 4     |
| source_class          | 2     |
| waterpoint_type       | 7     |
| year_recorded         | 5     |

Percentage of Missing/Null Values per Column:
|                       | 0   |
|:----------------------|:----|
| id                    | 0   |
| amount_tsh            | 0   |
| funder                | 0   |
| gps_height            | 0   |
| installer             | 0   |
| longitude             | 0   |
| latitude              | 0   |
| wpt_name              | 0   |
| basin                 | 0   |
| subvillage            | 0   |
| region                | 0   |
| region_code           | 0   |
| district_code         | 0   |
| population            | 0   |
| public_meeting        | 0   |
| scheme_management     | 0   |
| permit                | 0   |
| construction_year     | 0   |
| extraction_type_class | 0   |
| management_group      | 0   |
| payment_type          | 0   |
| quality_group         | 0   |
| quantity              | 0   |
| source_class          | 0   |
| waterpoint_type       | 0   |
| year_recorded         | 0   |

In [9]:
# Overview of cleaned train data
# train_data_cleaned = cleaner.clean_data(train_data, "Training")

In [10]:

# test_data_cleaned = cleaner.clean_data(test_data, "Test")